name: TradePlugin
version: '1.0'
main: by.kotor.trade.plugin.TradePlugin
api-version: '1.21'

commands:
  trade:
    description: Passing items in your hand to another player
    usage: /trade [player|accept|deny]
    aliases: [tr]
